/*
 * The music-zone table (sturdy-bassoon#90). See MusicZones.h for the format and ZoneDirector.h for
 * what reads it.
 *
 * EVERYTHING BETWEEN THE MARKERS IS GENERATED and a hand edit to it is lost on the next run. The
 * source is sturdy-bassoon/tools/music/zones.json; the generator is
 * sturdy-bassoon/tools/music/generate-zone-table.ts:
 *
 *     cd sturdy-bassoon/tools/grid-scene-tool
 *     npm run gen:music-zones            # rewrite the block
 *     npm run gen:music-zones -- --check # fail if the block is stale
 *
 * Outside the markers is this file's own scaffolding - the includes and the accessor functions the
 * runtime calls. That part is hand-written and the generator never touches it.
 *
 * The rows the generator currently emits are POC content on their way out; the format around them
 * is not. The generated block says so at length, in the words of the zone file itself.
 */

#include "MusicZones.h"

#include <stddef.h>

// The first-visit flags are named, not numbered - the number lives in exactly one place because it
// is serialized into save files (WorldFlagIds.h's own banner says so). The generator emits the
// enumerator and lets the compiler resolve it, so a renumbering there cannot silently disagree
// with a stale copy here.
#include "soh/Enhancements/rs/quest/WorldFlagIds.h"

extern "C" {
#include <z64.h>
#include "sequence.h"
#include "z64scene.h"
}

namespace {

// BEGIN RS MUSIC ZONE TABLE
// GENERATED by tools/music/generate-zone-table.ts from tools/music/zones.json
// (sturdy-bassoon#90 P1). DO NOT EDIT BETWEEN THE MARKERS - edit zones.json and re-run:
//     cd sturdy-bassoon/tools/grid-scene-tool && npm run gen:music-zones
// `npm run gen:music-zones -- --check` fails if this block is stale.

/*
 * The world-level music zone file (sturdy-bassoon#90 P1). This is the ONLY place zones are
 * authored. `npm run gen:music-zones` (from tools/grid-scene-tool) turns it into the block
 * between the BEGIN/END markers in
 * Shipwright/soh/soh/Enhancements/rs/music/MusicZoneTable.cpp. Never hand-edit that block:
 * the next generator run overwrites it. The format it emits is documented in MusicZones.h.
 *
 * TWO THINGS LIVE IN THIS FILE AND THEY HAVE OPPOSITE LIFETIMES.
 *
 * The FORMAT is permanent: rects in RS absolute tiles, priorities, the fallback, the optional
 * scene binding, the first-visit flag, the per-scene opt-in, the track list and its durations.
 * Build on it.
 *
 * The CONTENT below is a throwaway POC and is meant to be DELETED, not migrated. See
 * content_status.
 */

/*
 * EVERY ZONE BELOW IS POC CONTENT. Delete these rows when real terrain lands; do not migrate
 * them and do not build on the names.
 *
 * Only chunk rows 0 and 1 of the terrain grid - RS y 3392..3519 - are real RuneScape geography.
 * tools/terrain/f2p.json's own chunk_labels prefix rows 2-5 with '(mirror)' and '(copy)': they
 * are density stand-ins generated by tools/terrain/expand.py. Lumbridge Castle falls in chunk
 * [4,4], a mechanical copy of the Varrock Palace chunk, and the one composited settlement sits
 * in the Falador-north-gate chunk as a test placement.
 *
 * So RECTS ARE NAMED AFTER THE FIXTURE, NEVER AFTER A RUNESCAPE PLACE. P0 set that precedent
 * deliberately (settlement / west_fields / north_march / wilderness rather than lumbridge) so
 * that nothing downstream inherits a false premise about where it is.
 *
 * The TRACK LISTS AND DURATIONS added in P2 are POC on the same terms. They are vanilla OoT
 * sequences chosen to be told apart in a log, and their durations are a policy rather than a
 * measurement - see track_durations. Every one of them is replaced when #91 lands real audio.
 *
 * What makes throwing this away cheap is the coordinate frame: a rect authored against today's
 * fixture lives in the same frame as a rect authored against real Falador later. Replacing POC
 * content is deleting rows from this file, not migrating a format.
 */

/*
 * RS ABSOLUTE SURFACE TILES, y increasing NORTH. Not OoT world units, and not the terrain
 * toolchain's local 0..383 tile coordinates - both of those move when a bake window changes or
 * the world extent grows. RS's frame is anchored by Jagex and never moves.
 *
 * Anchor: RS (2944, 3519) == terrain tile (0, 0), so rsX = 2944 + tileX and rsY = 3519 - tileY.
 * The 6x6-chunk terrain extent covers RS x 2944..3327, y 3136..3519. Verified against the OSRS
 * Wiki's own map data in docs/decisions/2026-09-08-rs-terrain-coordinate-anchor.md, which also
 * records what that verification does NOT pin (map-square granularity, not tile).
 */

/*
 * THIS GENERATOR PERFORMS NO AXIS FLIP, AND MUST NOT GROW ONE.
 *
 * Its input (this file) and its output (the C table) are both in RS tiles, y north. Nothing to
 * convert. The single flip in the whole feature is RsMusicZones' WorldToRs() in
 * ZoneDirector.cpp, which turns OoT world Z (grows south) into RS y (grows north) at runtime.
 *
 * If someone later wants to author a rect in terrain-tile coordinates as a convenience, that
 * adds a SECOND negation, in a second place, and the two will disagree the first time one of
 * them is edited. Convert on the way in by hand and write the RS numbers here instead.
 */

/*
 * 1. DRAW A RECT TO THE VISUAL EDGE A PLAYER READS AS THE EDGE OF THE PLACE, NOT TO THE
 * AUTHORED FOOTPRINT OF THE GRID-TOOL PROJECT THAT CONTAINS IT.
 *
 * This is the first authoring rule the feature has produced from somebody listening to it
 * (#90, human tuning pass 2026-09-09). P0's `settlement` rect was the composited project's
 * footprint - terrain tiles x 56..118, y 64..143 - but the settlement's walls sit INSIDE
 * that footprint, so the music changed in open ground several tiles outside the visible
 * wall and there was no visual cue for where it happened. A project footprint is an
 * authoring convenience; it is not a thing the player can see.
 *
 * The `settlement` rect below is drawn to the wall instead - see its `derivation`.
 *
 * 2. Overlap is legal and is the intended way to nest. A high-priority rect sitting inside a
 * low-priority one is how you get 'the keep, inside the town, inside the fields' without
 * carving donut-shaped rect unions by hand. Coverage is total because exactly one zone
 * carries `fallback`.
 *
 * 3. A zone with an empty `tracks` list is authored SILENCE, and that is a legitimate choice.
 * It is not the same as leaving a hole - a hole means no zone matched, which only happens
 * if the fallback is removed.
 *
 * 4. A `firstVisitFlag` is serialized into save files. Its number is reserved BY HAND in
 * Shipwright's rs/quest/WorldFlagIds.h and named here; the generator never invents one and
 * refuses a name that is not in that header. POC zones take debug-band flags because their
 * content is going away; a real zone takes a production-band flag.
 *
 * 5. Y bands (`yMinUnits` / `yMaxUnits`, OoT world units) are for 'which floor of a building'.
 * Vertical space above ground inherits the ground zone, so leave them out unless you mean
 * it. Underground is separate scenes and binds by `sceneId` instead.
 *
 * 6. WITHIN A ZONE, EITHER EVERY TRACK CARRIES A `lengthSec` OR NONE OF THEM DOES. The
 * first-visit track counts as one of the zone's tracks for this. 0 means 'plays until
 * stopped', so a mixed list advances happily until it draws the 0 and then stops advancing
 * for the rest of the session - a dead end that looks exactly like the feature being
 * unfinished. The generator refuses the mix.
 *
 * 7. IF A ZONE HAS A FIRST-VISIT OPENER AND THE OPENER IS ALSO IN THE NORMAL TRACK LIST, the
 * shuffle bag will not follow the opener with itself - playing the opener counts as the
 * zone's just-played track for the back-to-back guard. That is a property worth relying on:
 * it means the intended opener can be an ordinary member of the rotation afterwards without
 * the first visit sounding like a stutter. `settlement` below is authored that way on
 * purpose, because it is the only arrangement in which the guard is observable.
 */

/*
 * `lengthSec` IS A DURATION TABLE, NOT A MEASURED LENGTH, and #90 section 9 chose it over
 * end-of-track detection deliberately. Read since P2.
 *
 * For a looping vanilla NA_BGM_* id the number is a POLICY - 'let this play for about this
 * long, then move on' - because the sequence data loops and would not end on its own. (That
 * vanilla BGM never ends is recorded as INFERRED rather than byte-verified, in AUDIO_SYSTEM.md
 * section 7; nothing here depends on resolving it, which is the point of a duration table.)
 *
 * For an imported RS track (#91) it will be the track's real length, which the importer already
 * has to know: a Looped="false" sequence requires a Length in seconds. So #91 should EMIT
 * durations rather than making somebody stopwatch them.
 *
 * 0 keeps its old meaning, 'plays until stopped', and a zone whose tracks are all 0 never
 * advances at all. That is what every zone did through P1 and it stays valid - `north_march`
 * below is authored that way on purpose so the behaviour has a live example rather than only a
 * sentence.
 *
 * The director also advances when sequence player 0 goes quiet on its own, whichever comes
 * first. That is opportunistic and never the mechanism: see 'one end-of-track handler, two
 * triggers' in ZoneDirector.h.
 */

/*
 * `conditions` is in the format and is NOT read by the runtime. It is the day/night and weather
 * axis (#90 non-goals), kept as a field so adding that axis later costs nothing. Emitting it now
 * is deliberate; reading it is not this phase's job.
 *
 * (`lengthSec` used to be listed here. It is read as of P2 - see track_durations.)
 */

/*
 * Scene-bound: no rects, matches the whole of SCENE_GRID_TEST_MAP_10. This is the shape #90 section 4
 * reserves for underground areas, which are planned as separate scenes anyway (fewer tris, easier to edit,
 * and you can never see the surface from below) and should not be forced to share the surface queue.
 * Priority is not what decides this - the scene binding is - but it is set high so that a future surface
 * rect drawn over the same scene id cannot quietly outrank it.
 */
const RsZoneTrack kTracks_test_map_interior[] = {
    { NA_BGM_INSIDE_DEKU_TREE, RS_ZONE_COND_ANY, 0 },
};

/*
 * POC. A rect strictly inside `settlement`, which is strictly inside `west_fields` - three priority levels
 * nested without a single donut-shaped union. It corresponds to no authored feature; it exists so priority
 * resolution is exercised by something that really is enclosed, which P0's table never had (its
 * `settlement` won on its own rect with nothing around it). Single track, no duration: a one-track zone
 * that plays until you leave it, which is the P1 shape and still the right one for a small interior.
 */
const RsZoneRect kRects_settlement_core[] = {
    { 3024, 3404, 3043, 3429, RS_ZONE_Y_ANY_MIN, RS_ZONE_Y_ANY_MAX },
};
const RsZoneTrack kTracks_settlement_core[] = {
    { NA_BGM_LINK_HOUSE, RS_ZONE_COND_ANY, 0 },
};

/*
 * POC. The composited settlement, drawn to its WALL rather than to the grid-tool project's footprint -
 * authoring rule 1. Multi-track since P2, and authored to make the opener interaction observable:
 * NA_BGM_MARKET is BOTH the one-shot opener and an ordinary member of the rotation, so the shuffle bag's
 * very first draw after the opener is the one place the back-to-back guard can be caught doing its job. If
 * it ever draws 0x1D straight after the first-visit 0x1D, the guard is broken.
 *
 * Derivation:
 * `Lumbridge Settlement X3` is 62x79 tiles placed at terrain tile (56,64), and the composite rotates it 180
 * degrees about the footprint centre, so grid cell (gx,gy) lands on terrain tile (118-gx, 143-gy). Its
 * authored geometry occupies grid cells x 1..55, y 6..74 (the bounding box of every wall edge across all
 * three levels), i.e. grid extent x 1..56, y 6..75 - so terrain x 62..117, y 68..137, so RS x 3006..3061, y
 * 3382..3451. The footprint P0 used was RS x 3000..3062, y 3376..3455: up to 6 tiles of open ground outside
 * the wall on three sides, which is precisely what was audible.
 */
const RsZoneRect kRects_settlement[] = {
    { 3006, 3382, 3061, 3451, RS_ZONE_Y_ANY_MIN, RS_ZONE_Y_ANY_MAX },
};
const RsZoneTrack kTracks_settlement[] = {
    { NA_BGM_KAKARIKO_KID, RS_ZONE_COND_ANY, 55 },
    { NA_BGM_MARKET, RS_ZONE_COND_ANY, 45 },
    { NA_BGM_SHOP, RS_ZONE_COND_ANY, 35 },
};
const RsZoneTrack kFirstVisit_settlement[] = { { NA_BGM_MARKET, RS_ZONE_COND_ANY, 45 } };

/*
 * POC. The open ground the settlement stands in, and the zone Link spawns in - which is why it carries the
 * longest track list: it is where a full bag cycle can be watched without moving. Four tracks, all with
 * durations, so one cycle plus the refill draw that follows it runs a little under four minutes. Widened
 * from P0's x 2944..2999 to cover the whole block, so that the ground between the old footprint edge and
 * the actual wall now sounds like the fields - the audible form of authoring rule 1 and the one thing a
 * teleport can demonstrate about it.
 */
const RsZoneRect kRects_west_fields[] = {
    { 2944, 3376, 3062, 3455, RS_ZONE_Y_ANY_MIN, RS_ZONE_Y_ANY_MAX },
};
const RsZoneTrack kTracks_west_fields[] = {
    { NA_BGM_KOKIRI, RS_ZONE_COND_ANY, 45 },
    { NA_BGM_SARIA_THEME, RS_ZONE_COND_ANY, 40 },
    { NA_BGM_FIELD_MORNING, RS_ZONE_COND_ANY, 35 },
    { NA_BGM_WINDMILL, RS_ZONE_COND_ANY, 50 },
};

/*
 * POC. Same x band as `west_fields`, different y band - kept from P0 because it is the check that proves
 * the north/south axis, which is the one that flips. Since P2 it is also the LIVE EXAMPLE OF lengthSec 0:
 * three tracks and not one duration between them, so it picks a track on activation and then never
 * advances, however long you stand in it. That is P1's behaviour and it is still valid; it has a zone
 * rather than only a sentence so a run can assert the negative against something that would obviously move
 * if the rule were wrong.
 */
const RsZoneRect kRects_north_march[] = {
    { 2944, 3456, 3062, 3519, RS_ZONE_Y_ANY_MIN, RS_ZONE_Y_ANY_MAX },
};
const RsZoneTrack kTracks_north_march[] = {
    { NA_BGM_GERUDO_VALLEY, RS_ZONE_COND_ANY, 0 },
    { NA_BGM_ZORA_DOMAIN, RS_ZONE_COND_ANY, 0 },
    { NA_BGM_GORON_CITY, RS_ZONE_COND_ANY, 0 },
};

/*
 * The fallback: no rects, matches everywhere, lowest priority. It is what makes coverage total, so every
 * point in every opted-in scene has an answer and the director never falls silent by accident. Removing it
 * does not create silence - it creates a hole.
 */
const RsZoneTrack kTracks_wilderness[] = {
    { NA_BGM_LONLON, RS_ZONE_COND_ANY, 0 },
};

/*
 * The table. Order is not significant: ResolveZone scans all of it and takes the highest
 * priority that matches, with ties going to the earlier entry so the answer is a pure
 * function of this file rather than of iteration order elsewhere.
 */
const RsMusicZone kZones[] = {
    {
        .name = "test_map_interior",
        .priority = 50,
        .sceneId = SCENE_GRID_TEST_MAP_10,
        .firstVisitFlag = RS_ZONE_NO_FIRST_VISIT,
        .flags = 0,
        .rectCount = 0,
        .trackCount = 1,
        .rects = NULL,
        .tracks = kTracks_test_map_interior,
        .firstVisitTrack = NULL,
    },
    {
        .name = "settlement_core",
        .priority = 30,
        .sceneId = RS_ZONE_SCENE_ANY,
        .firstVisitFlag = RS_ZONE_NO_FIRST_VISIT,
        .flags = 0,
        .rectCount = 1,
        .trackCount = 1,
        .rects = kRects_settlement_core,
        .tracks = kTracks_settlement_core,
        .firstVisitTrack = NULL,
    },
    {
        .name = "settlement",
        .priority = 20,
        .sceneId = RS_ZONE_SCENE_ANY,
        .firstVisitFlag = WORLD_FLAG_MUSIC_FIRST_VISIT_SETTLEMENT,
        .flags = 0,
        .rectCount = 1,
        .trackCount = 3,
        .rects = kRects_settlement,
        .tracks = kTracks_settlement,
        .firstVisitTrack = kFirstVisit_settlement,
    },
    {
        .name = "west_fields",
        .priority = 10,
        .sceneId = RS_ZONE_SCENE_ANY,
        .firstVisitFlag = RS_ZONE_NO_FIRST_VISIT,
        .flags = 0,
        .rectCount = 1,
        .trackCount = 4,
        .rects = kRects_west_fields,
        .tracks = kTracks_west_fields,
        .firstVisitTrack = NULL,
    },
    {
        .name = "north_march",
        .priority = 10,
        .sceneId = RS_ZONE_SCENE_ANY,
        .firstVisitFlag = RS_ZONE_NO_FIRST_VISIT,
        .flags = 0,
        .rectCount = 1,
        .trackCount = 3,
        .rects = kRects_north_march,
        .tracks = kTracks_north_march,
        .firstVisitTrack = NULL,
    },
    {
        .name = "wilderness",
        .priority = -32768,
        .sceneId = RS_ZONE_SCENE_ANY,
        .firstVisitFlag = RS_ZONE_NO_FIRST_VISIT,
        .flags = RS_ZONE_FLAG_FALLBACK,
        .rectCount = 0,
        .trackCount = 1,
        .rects = NULL,
        .tracks = kTracks_wilderness,
        .firstVisitTrack = NULL,
    },
};

/*
 * Per-scene opt-in. A scene that is not in this list is untouched: the vanilla loader still
 * sets its music and the director never runs there. Opt-in rather than global because there
 * are ~20 generated grid-tool scenes plus all of vanilla, and this table describes only F2P.
 */
const RsMusicScene kScenes[] = {
   /*
    * SUPERSEDED for testing by SCENE_TERRAIN_F2P_SETTLEMENT_SEALED below, and kept opted in on purpose.
    * This bake (0x83, `entrance 0x62C`) predates the #95 T-junction fix and tears along seams; it is
    * retained as the walkable 'before' half of that A/B, and keeping it in this table means the tearing can
    * be compared with the music working in both.
    *
    * Derivation:
    * HAND-DERIVED; deriving this belongs to the world manifest (#92), not here. The scene's collision
    * bounds are (-7680,-7680)..(7680,7680) - 384 tiles of 40 units, recentred on the bake window - so
    * terrain tile (0,0) is at world (-7680,-7680) and OoT world (0,0) is terrain tile (192,192) = RS
    * (2944+192, 3519-192) = (3136, 3327). Cross-checked against the emitted spawn ActorEntry at
    * (-6640,13,-2960), which must be f2p.json's authored spawn tile (26,118): 26*40-7680 = -6640 and
    * 118*40-7680 = -2960. It is. A re-bake with a different window silently invalidates this; `rsmusic
    * where` shows the drift in one teleport.
    */
    {
        .sceneId = SCENE_TERRAIN_F2P_SETTLEMENT,
        .rsOriginX = 3136,
        .rsOriginY = 3327,
        .unitsPerTile = 40,
        .flags = 0,
    },
   /*
    * THE ONE TO TEST AUDIO IN (0x8A, `entrance 0x633`). Same bake as SCENE_TERRAIN_F2P_SETTLEMENT above -
    * same field, same `Lumbridge Settlement X3@56,64` composite, same everything - re-emitted 2026-09-10
    * through the C exporter with #95's T-junctions closed, so the seams no longer tear. Prefer it for
    * anything a human has to look at while listening.
    *
    * Derivation:
    * IDENTICAL to SCENE_TERRAIN_F2P_SETTLEMENT's, and that is checked rather than assumed. The anchor is a
    * function of the bake window, and the re-emit reported the same collision bounds
    * (-7680,-7680)..(7680,7680) and the same spawn ActorEntry (-6640,13,-2960) as the original - so the
    * recentred origin did not move and the derivation above carries over unchanged. Closing T-junctions
    * splits edges and adds vertices; it does not move the window. If a future re-bake changes `--chunks` or
    * the field, this number stops being right for BOTH scenes at once: `rsmusic where` at the spawn must
    * read rs=2970,3401.
    */
    {
        .sceneId = SCENE_TERRAIN_F2P_SETTLEMENT_SEALED,
        .rsOriginX = 3136,
        .rsOriginY = 3327,
        .unitsPerTile = 40,
        .flags = 0,
    },
   /*
    * POC stand-in for an interior / underground scene (0x76, `entrance 0x61F`). It exists in this table to
    * exercise the scene-bound zone path - a small grid-tool test map with its own local origin, which is
    * exactly the shape an underground scene will have.
    *
    * Derivation:
    * None, and that is the point. This scene's world origin does not sit anywhere in the surface coordinate
    * frame, so it carries no anchor and rect matching is skipped entirely inside it. Without that, a dummy
    * anchor's meaningless RS tiles would land inside some surface rect and a surface zone would beat the
    * scene-bound one.
    */
    {
        .sceneId = SCENE_GRID_TEST_MAP_10,
        .rsOriginX = 0,
        .rsOriginY = 0,
        .unitsPerTile = 0,
        .flags = RS_SCENE_FLAG_NO_SURFACE_ANCHOR,
    },
};
// END RS MUSIC ZONE TABLE

} // namespace

extern "C" const RsMusicZone* RsMusicZones_All(int32_t* count) {
    if (count != NULL) {
        *count = (int32_t)(sizeof(kZones) / sizeof(kZones[0]));
    }
    return kZones;
}

extern "C" int32_t RsMusicZones_Count(void) {
    return (int32_t)(sizeof(kZones) / sizeof(kZones[0]));
}

extern "C" const RsMusicZone* RsMusicZones_At(int32_t index) {
    if (index < 0 || index >= RsMusicZones_Count()) {
        return NULL;
    }
    return &kZones[index];
}

extern "C" const RsMusicScene* RsMusicZones_Scene(int16_t sceneId) {
    for (size_t i = 0; i < sizeof(kScenes) / sizeof(kScenes[0]); i++) {
        if (kScenes[i].sceneId == sceneId) {
            return &kScenes[i];
        }
    }
    return NULL;
}

extern "C" int32_t RsMusicZones_SceneCount(void) {
    return (int32_t)(sizeof(kScenes) / sizeof(kScenes[0]));
}

extern "C" const RsMusicScene* RsMusicZones_SceneAt(int32_t index) {
    if (index < 0 || index >= RsMusicZones_SceneCount()) {
        return NULL;
    }
    return &kScenes[index];
}
