#include "CustomWorldExportWest173SyntheticScene.h"
#include "global.h"
#include "z64scene.h"
#include "macros.h"
#include "soh/Enhancements/game-interactor/GameInteractor_Hooks.h"
#include "soh/OTRGlobals.h"
#include "soh/ActorDB.h"
#include <spdlog/spdlog.h>
#include "../GridToolSceneData.h"
#include "soh/Enhancements/staticbake/ArchivePropLists.h"
#include "soh/Enhancements/rs/actors/RsActorParams.h"

// Generated by tools/grid-scene-tool. Re-exporting the same project regenerates this file -
// hand edits will be overwritten.

extern "C" ActorDBEntry* ActorDB_Retrieve(const int id);

extern "C" {
    extern CollisionHeader world_export_west_173_synthetic_scene_collisionHeader;
    extern RoomShapeNormal world_export_west_173_synthetic_room_0_shapeHeader;

    extern s16   gLinkObjectIds[];
    s32  Object_Spawn(ObjectContext* objectCtx, s16 objectId);
    void BgCheck_Allocate(CollisionContext* colCtx, PlayState* play, CollisionHeader* colHeader);
    void Play_InitEnvironment(PlayState* play, s16 skyboxId);
    u32  func_80096FE8(PlayState* play, RoomContext* roomCtx);
    void func_80096FD4(PlayState* play, Room* room);
    void Player_SetBootData(PlayState* play, Player* player);
    void Actor_SpawnTransitionActors(PlayState* play, ActorContext* actorCtx);
    void Object_InitBank(PlayState* play, ObjectContext* objectCtx);
    void LightContext_Init(PlayState* play, LightContext* lightCtx);
    void TransitionActor_InitContext(GameState* state, TransitionActorContext* transiActorCtx);
}

// Default 4-entry (dawn/day/dusk/night) lighting - flat/generic for v1, no per-scene lighting
// authoring in the grid tool yet.
static EnvLightSettings sWorldExportWest173SyntheticLightSettings[4] = {
    {{ 70, 45, 57 }, { 73, -73, 73 }, { 180, 154, 138 }, { -73, 73, -73 }, { 20, 20, 60 },
     { 140, 120, 100 }, (s16)(993 | (1 << 10)), 12800 },
    {{ 105, 90, 90 }, { 73, -73, 73 }, { 255, 255, 240 }, { -73, 73, -73 }, { 50, 50, 90 },
     { 100, 100, 120 }, (s16)(996 | (1 << 10)), 12800 },
    {{ 120, 90, 0 }, { 73, -73, 73 }, { 250, 135, 50 }, { -73, 73, -73 }, { 30, 30, 60 },
     { 120, 70, 50 }, (s16)(995 | (1 << 10)), 12800 },
    {{ 40, 70, 100 }, { 73, -73, 73 }, { 20, 20, 35 }, { -73, 73, -73 }, { 50, 50, 100 },
     { 0, 0, 30 }, (s16)(992 | (1 << 10)), 12800 },
};

// v1 scope has no multi-entrance/exit support - a single spawn index 0.
static EntranceEntry sWorldExportWest173SyntheticEntrances[] = {
    { 0, 0 },
};

// Spawn point authored in the grid tool (grid-space -> world units, see src/shared/geometry.ts).
// params: bits 8-11 = PLAYER_START_MODE_IDLE (0xD - see PLAYER_GET_START_MODE in z64player.h;
// mode 0 is PLAYER_START_MODE_NOTHING, which leaves Player's update/draw entirely inert), low
// byte 0xFF = "no start bg-camera override" (we don't author per-scene camera data).
static ActorEntry sWorldExportWest173SyntheticPlayerSpawn = {
    ACTOR_PLAYER, { -20, 0, 20 }, { 0, 0, 0 }, 0xDFF
};

// 2 staircase placements (sturdy-bassoon#173), one per storey a staircase serves.
static ActorEntry sWorldExportWest173SyntheticActors[2] = {
    { ACTOR_RS_STAIRS, { 420, 0, -20 }, { 0, -0x4000, 0 }, RS_STAIR_PARAMS(7948, 0) }, // staircase "West stair" row 0: level 0 at (21, 31) facing E
    { ACTOR_RS_STAIRS, { 420, 84, -20 }, { 0, -0x4000, 0 }, RS_STAIR_PARAMS(7948, 1) }, // staircase "West stair" row 1: level 1 at (21, 31) facing E
};

static RomFile sWorldExportWest173SyntheticRoomList[] = {
    { (uintptr_t)&world_export_west_173_synthetic_room_0_shapeHeader,
      (uintptr_t)&world_export_west_173_synthetic_room_0_shapeHeader + 256,
      nullptr },
};

extern "C" int CustomWorldExportWest173SyntheticScene_IsCustomScene(s32 sceneId) {
    return sceneId == SCENE_WORLD_EXPORT_WEST_173_SYNTHETIC;
}

static void InitScene(PlayState* play, s32 spawn) {
    play->curSpawn          = spawn;
    play->linkActorEntry    = nullptr;
    play->unk_11DFC         = nullptr;
    play->setupEntranceList = nullptr;
    play->setupExitList     = nullptr;
    play->cUpElfMsgs        = nullptr;
    play->setupPathList     = nullptr;
    play->numSetupActors    = 0;

    Object_InitBank(play, &play->objectCtx);
    LightContext_Init(play, &play->lightCtx);
    TransitionActor_InitContext(&play->state, &play->transiActorCtx);
    func_80096FD4(play, &play->roomCtx.curRoom);
    YREG(15) = 0;
    gSaveContext.worldMapArea = 0;

    BgCheck_Allocate(&play->colCtx, play, &world_export_west_173_synthetic_scene_collisionHeader);

    play->numRooms = 1;
    play->roomList = sWorldExportWest173SyntheticRoomList;

    play->setupEntranceList = sWorldExportWest173SyntheticEntrances;
    play->linkActorEntry    = &sWorldExportWest173SyntheticPlayerSpawn;
    play->linkAgeOnLoad     = gSaveContext.linkAge;

    s16 linkObjectId = gLinkObjectIds[gSaveContext.linkAge];
    ActorDB_Retrieve(play->linkActorEntry->id)->objectId = linkObjectId;
    Object_Spawn(&play->objectCtx, linkObjectId);

    play->objectCtx.subKeepIndex = Object_Spawn(&play->objectCtx, OBJECT_GAMEPLAY_FIELD_KEEP);

    play->skyboxId = SKYBOX_NORMAL_SKY;
    // What SCENE_CMD_SKYBOX_SETTINGS and SCENE_CMD_SKYBOX_DISABLES set in a normal scene: a clear
    // sky, outdoors, sky and sun drawn. PlayState is re-allocated for each scene without being
    // cleared, so skipping them left the previous scene's values in place - Hyrule Field's storm,
    // Link's house's indoor lighting (sturdy-bassoon#122).
    play->envCtx.unk_17 = play->envCtx.unk_18 = 0;
    play->envCtx.indoors         = 0;
    play->envCtx.skyboxDisabled  = 0;
    play->envCtx.sunMoonDisabled = 0;
    play->sequenceCtx.seqId            = NA_BGM_KAKARIKO_KID;
    // NATURE_ID_NONE, never 0xFF: that is NATURE_ID_DISABLED, a save-context value past the end of
    // the ambience table, which z_kankyo.c played at dusk and crashed the audio thread (sturdy-bassoon#156).
    play->sequenceCtx.natureAmbienceId = NATURE_ID_NONE;

    // Normal scenes get this from SCENE_CMD_SOUND_SETTINGS, which resets the audio heap/SFX
    // banks. Our hand-rolled init bypasses the scene command list entirely, so without this call
    // player SFX (footsteps, jump, roll, etc.) and all other one-shot sound effects are silently
    // dropped later in the audio pipeline (BGM is unaffected - it doesn't go through this reset).
    Audio_QueueSeqCmd(0xF0000000);

    play->envCtx.numLightSettings  = 4;
    play->envCtx.lightSettingsList = sWorldExportWest173SyntheticLightSettings;

    Play_InitEnvironment(play, play->skyboxId);
    GameInteractor_ExecuteAfterSceneCommands(play->sceneNum);
}

// The archive prop lists this room draws (sturdy-bassoon#171): plain archive paths, resolved at
// load and baked. Always emitted, so a map's first prop needs no build - only its archive.
static const char* const sWorldExportWest173SyntheticPropLists[] = { "objects/rs_props/world_export_west_173_synthetic/props" };

extern "C" void CustomWorldExportWest173SyntheticScene_InitRoom(PlayState* play, RoomContext* roomCtx) {
    roomCtx->curRoom.echo       = 0;
    roomCtx->curRoom.meshHeader = (MeshHeader*)&world_export_west_173_synthetic_room_0_shapeHeader;

    // Normal scenes get these from SCENE_CMD_ROOM_BEHAVIOR; this hand-rolled init bypasses the
    // scene command list, and nothing on the load path clears them - func_80096FD4 resets only
    // num/segment. Without them the room inherits the previous scene's values: a stale
    // ROOM_BEHAVIOR_TYPE1_2 caps R_RUN_SPEED_LIMIT to 5.0 (the short ledge hop instead of the
    // run-off leap) and disables backflip/sidehop/roll. See issue #39.
    roomCtx->curRoom.behaviorType1 = ROOM_BEHAVIOR_TYPE1_0;
    roomCtx->curRoom.behaviorType2 = ROOM_BEHAVIOR_TYPE2_0;
    roomCtx->curRoom.lensMode      = LENS_MODE_HIDE_ACTORS;

    // 2 entries; play->numSetupActors is an s16 (sturdy-bassoon#45), so this is
    // the authored count and not a truncation of it.
    play->numSetupActors = 2;
    play->setupActorList = sWorldExportWest173SyntheticActors;

    ArchiveProps_DeclareRoom(play, roomCtx, sWorldExportWest173SyntheticPropLists, ARRAY_COUNT(sWorldExportWest173SyntheticPropLists));

    Player_SetBootData(play, GET_PLAYER(play));
    Actor_SpawnTransitionActors(play, &play->actorCtx);
    GameInteractor_ExecuteAfterSceneCommands(play->sceneNum);
}

extern "C" int CustomWorldExportWest173SyntheticScene_TrySpawn(PlayState* play, s32 sceneId, s32 spawn) {
    if (sceneId != SCENE_WORLD_EXPORT_WEST_173_SYNTHETIC) {
        return 0;
    }

    SceneTableEntry* scene = &gSceneTable[sceneId];
    scene->unk_13      = 0;
    play->loadedScene  = scene;
    play->sceneNum     = sceneId;
    play->sceneConfig  = scene->config;
    play->sceneSegment = nullptr;

    InitScene(play, spawn);
    func_80096FE8(play, &play->roomCtx);
    GameInteractor_ExecuteOnSceneInit(play->sceneNum);

    SPDLOG_INFO("CustomWorldExportWest173SyntheticScene: spawned scene {} spawn {}", sceneId, spawn);
    return 1;
}
