#include "CustomTerrainF2pRooms2x2Scene.h"
#include "global.h"
#include "z64scene.h"
#include "macros.h"
#include "soh/Enhancements/game-interactor/GameInteractor_Hooks.h"
#include "soh/OTRGlobals.h"
#include "soh/ActorDB.h"
#include <spdlog/spdlog.h>
#include <cstring>
#include "../GridToolSceneData.h"

// Generated by tools/terrain/integrate-fast64.ts from a Fast64 export.
// f2p-greybox chunks [0, 0, 1, 1] step 3, 43x43 cells, 4 room(s)
// Re-running the generator overwrites this file - hand edits will be lost.

extern "C" ActorDBEntry* ActorDB_Retrieve(const int id);

extern "C" {
    extern CollisionHeader terrain_f2p_rooms_2x2_scene_collisionHeader;
    extern EnvLightSettings terrain_f2p_rooms_2x2_scene_header00_lightSettings[4];
    extern RoomShapeNormal terrain_f2p_rooms_2x2_room_0_shapeHeader;
    extern RoomShapeNormal terrain_f2p_rooms_2x2_room_1_shapeHeader;
    extern RoomShapeNormal terrain_f2p_rooms_2x2_room_2_shapeHeader;
    extern RoomShapeNormal terrain_f2p_rooms_2x2_room_3_shapeHeader;
    extern TransitionActorEntry terrain_f2p_rooms_2x2_scene_header00_transitionActors[];

    extern s16   gLinkObjectIds[];
    s32  Object_Spawn(ObjectContext* objectCtx, s16 objectId);
    void BgCheck_Allocate(CollisionContext* colCtx, PlayState* play, CollisionHeader* colHeader);
    void Play_InitEnvironment(PlayState* play, s16 skyboxId);
    u32  func_80096FE8(PlayState* play, RoomContext* roomCtx);
    void func_80096FD4(PlayState* play, Room* room);
    void Player_SetBootData(PlayState* play, Player* player);
    void Actor_SpawnTransitionActors(PlayState* play, ActorContext* actorCtx);
    void Object_InitBank(PlayState* play, ObjectContext* objectCtx);
    void LightContext_Init(PlayState* play, LightContext* lightCtx);
    void TransitionActor_InitContext(GameState* state, TransitionActorContext* transiActorCtx);
}

// One spawn point. EntranceEntry is { spawn actor index, room }, and func_80096FE8 reads the room
// out of it to decide which room to load first - so this has to be the room the spawn position is
// physically inside, not room 0, or Link starts standing over unloaded geometry.
static EntranceEntry sTerrainF2pRooms2x2Entrances[] = {
    { 0, 2 },
};

// The same spawn Fast64 wrote into terrain_f2p_rooms_2x2_scene_header00_playerEntryList, taken from the
// generator's sidecar rather than that array because the engine wants it as a plain ActorEntry
// and nothing here executes the spawn list command that would have found it.
// params: bits 8-11 = PLAYER_START_MODE_IDLE (0xD - see PLAYER_GET_START_MODE in z64player.h;
// mode 0 is PLAYER_START_MODE_NOTHING, which leaves Player's update/draw entirely inert), low
// byte 0xFF = "no start bg-camera override".
static ActorEntry sTerrainF2pRooms2x2PlayerSpawn = {
    ACTOR_PLAYER, { -1540, 13, 2140 }, { 0, -32768, 0 }, 0xDFF
};

// vromStart is read as a direct pointer for compiled-in rooms (see OTRRoom_RequestNewRoom); the
// +256 end is only used to size a room buffer that this path never fills.
static RomFile sTerrainF2pRooms2x2RoomList[] = {
    { (uintptr_t)&terrain_f2p_rooms_2x2_room_0_shapeHeader,
      (uintptr_t)&terrain_f2p_rooms_2x2_room_0_shapeHeader + 256,
      nullptr },
    { (uintptr_t)&terrain_f2p_rooms_2x2_room_1_shapeHeader,
      (uintptr_t)&terrain_f2p_rooms_2x2_room_1_shapeHeader + 256,
      nullptr },
    { (uintptr_t)&terrain_f2p_rooms_2x2_room_2_shapeHeader,
      (uintptr_t)&terrain_f2p_rooms_2x2_room_2_shapeHeader + 256,
      nullptr },
    { (uintptr_t)&terrain_f2p_rooms_2x2_room_3_shapeHeader,
      (uintptr_t)&terrain_f2p_rooms_2x2_room_3_shapeHeader + 256,
      nullptr },
};

// Actor_SpawnTransitionActors negates each entry's id as it spawns it, using the sign as its
// "already done" marker. A scene loaded from ROM gets a fresh copy of the list in a segment buffer
// on every load, so that mutation is invisible; a compiled-in list is the same memory every time,
// and the second visit to this scene would find every id already negative and spawn no room
// transitions at all. So the exported array is treated as read-only and copied into this working
// buffer on each scene init.
static TransitionActorEntry sTerrainF2pRooms2x2TransitionActors[28];

extern "C" int CustomTerrainF2pRooms2x2Scene_IsCustomScene(s32 sceneId) {
    return sceneId == SCENE_TERRAIN_F2P_ROOMS_2X2;
}

static void InitScene(PlayState* play, s32 spawn) {
    play->curSpawn          = spawn;
    play->linkActorEntry    = nullptr;
    play->unk_11DFC         = nullptr;
    play->setupEntranceList = nullptr;
    play->setupExitList     = nullptr;
    play->cUpElfMsgs        = nullptr;
    play->setupPathList     = nullptr;
    play->numSetupActors    = 0;

    Object_InitBank(play, &play->objectCtx);
    LightContext_Init(play, &play->lightCtx);
    TransitionActor_InitContext(&play->state, &play->transiActorCtx);
    func_80096FD4(play, &play->roomCtx.curRoom);
    YREG(15) = 0;
    gSaveContext.worldMapArea = 0;

    BgCheck_Allocate(&play->colCtx, play, &terrain_f2p_rooms_2x2_scene_collisionHeader);

    // Collision stays scene-wide however many rooms there are: SCENE_CMD_ID_COLLISION_HEADER is a
    // scene command, not a room one. Rooms split render geometry and actors only.
    // The casts here and below are not decoration: numRooms and numActors are both u8, ARRAY_COUNT
    // is a size_t, and this fork builds /W3 /WX.
    play->numRooms = (u8)ARRAY_COUNT(sTerrainF2pRooms2x2RoomList);
    play->roomList = sTerrainF2pRooms2x2RoomList;

    memcpy(sTerrainF2pRooms2x2TransitionActors, terrain_f2p_rooms_2x2_scene_header00_transitionActors, sizeof(sTerrainF2pRooms2x2TransitionActors));
    play->transiActorCtx.numActors = (u8)ARRAY_COUNT(sTerrainF2pRooms2x2TransitionActors);
    play->transiActorCtx.list      = sTerrainF2pRooms2x2TransitionActors;

    play->setupEntranceList = sTerrainF2pRooms2x2Entrances;
    play->linkActorEntry    = &sTerrainF2pRooms2x2PlayerSpawn;
    play->linkAgeOnLoad     = gSaveContext.linkAge;

    s16 linkObjectId = gLinkObjectIds[gSaveContext.linkAge];
    ActorDB_Retrieve(play->linkActorEntry->id)->objectId = linkObjectId;
    Object_Spawn(&play->objectCtx, linkObjectId);

    play->objectCtx.subKeepIndex = Object_Spawn(&play->objectCtx, OBJECT_GAMEPLAY_FIELD_KEEP);

    play->skyboxId = SKYBOX_NORMAL_SKY;
    play->sequenceCtx.seqId            = NA_BGM_FIELD_LOGIC;
    play->sequenceCtx.natureAmbienceId = 0xFF;

    // Normal scenes get this from SCENE_CMD_SOUND_SETTINGS, which resets the audio heap/SFX
    // banks. Our hand-rolled init bypasses the scene command list entirely, so without this call
    // player SFX (footsteps, jump, roll, etc.) and all other one-shot sound effects are silently
    // dropped later in the audio pipeline (BGM is unaffected - it doesn't go through this reset).
    Audio_QueueSeqCmd(0xF0000000);

    // Fast64's own light settings, exported alongside the geometry, so the lighting is something
    // the .blend can be edited to change rather than a constant baked into this template.
    play->envCtx.numLightSettings  = ARRAY_COUNT(terrain_f2p_rooms_2x2_scene_header00_lightSettings);
    play->envCtx.lightSettingsList = terrain_f2p_rooms_2x2_scene_header00_lightSettings;

    Play_InitEnvironment(play, play->skyboxId);
    GameInteractor_ExecuteAfterSceneCommands(play->sceneNum);
}

extern "C" void CustomTerrainF2pRooms2x2Scene_InitRoom(PlayState* play, RoomContext* roomCtx) {
    // Called once at scene load and again on every room change; roomCtx->curRoom.num has already
    // been set to the room being entered by OTRRoom_RequestNewRoom.
    static MeshHeader* const shapeHeaders[] = {
        (MeshHeader*)&terrain_f2p_rooms_2x2_room_0_shapeHeader,
        (MeshHeader*)&terrain_f2p_rooms_2x2_room_1_shapeHeader,
        (MeshHeader*)&terrain_f2p_rooms_2x2_room_2_shapeHeader,
        (MeshHeader*)&terrain_f2p_rooms_2x2_room_3_shapeHeader,
    };
    s32 room = roomCtx->curRoom.num;
    if (room < 0 || room >= (s32)ARRAY_COUNT(shapeHeaders)) {
        SPDLOG_WARN("CustomTerrainF2pRooms2x2Scene: room {} out of range, drawing room 0", room);
        room = 0;
    }

    roomCtx->curRoom.echo       = 0;
    roomCtx->curRoom.meshHeader = shapeHeaders[room];

    // No per-room actor placement yet - Link spawns via linkActorEntry, and the only other actors
    // are the room-transition planes, which come from the transition list rather than this one.
    play->numSetupActors = 0;
    play->setupActorList = nullptr;

    Player_SetBootData(play, GET_PLAYER(play));
    Actor_SpawnTransitionActors(play, &play->actorCtx);
    GameInteractor_ExecuteAfterSceneCommands(play->sceneNum);
}

extern "C" int CustomTerrainF2pRooms2x2Scene_TrySpawn(PlayState* play, s32 sceneId, s32 spawn) {
    if (sceneId != SCENE_TERRAIN_F2P_ROOMS_2X2) {
        return 0;
    }

    SceneTableEntry* scene = &gSceneTable[sceneId];
    scene->unk_13      = 0;
    play->loadedScene  = scene;
    play->sceneNum     = sceneId;
    play->sceneConfig  = scene->config;
    play->sceneSegment = nullptr;

    InitScene(play, spawn);
    func_80096FE8(play, &play->roomCtx);
    GameInteractor_ExecuteOnSceneInit(play->sceneNum);

    SPDLOG_INFO("CustomTerrainF2pRooms2x2Scene: spawned scene {} spawn {} ({} rooms)", sceneId, spawn,
                ARRAY_COUNT(sTerrainF2pRooms2x2RoomList));
    return 1;
}
