#include "CustomStairsWarpsF3173Scene.h"
#include "global.h"
#include "z64scene.h"
#include "macros.h"
#include "soh/Enhancements/game-interactor/GameInteractor_Hooks.h"
#include "soh/OTRGlobals.h"
#include "soh/ActorDB.h"
#include <spdlog/spdlog.h>
#include "../GridToolSceneData.h"
#include "soh/Enhancements/staticbake/ArchivePropLists.h"
#include "soh/Enhancements/rs/actors/RsActorParams.h"

// Generated by tools/grid-scene-tool. Re-exporting the same project regenerates this file -
// hand edits will be overwritten.

extern "C" ActorDBEntry* ActorDB_Retrieve(const int id);

extern "C" {
    extern CollisionHeader stairs_warps_f3_173_scene_collisionHeader;
    extern RoomShapeNormal stairs_warps_f3_173_room_0_shapeHeader;

    extern s16   gLinkObjectIds[];
    s32  Object_Spawn(ObjectContext* objectCtx, s16 objectId);
    void BgCheck_Allocate(CollisionContext* colCtx, PlayState* play, CollisionHeader* colHeader);
    void Play_InitEnvironment(PlayState* play, s16 skyboxId);
    u32  func_80096FE8(PlayState* play, RoomContext* roomCtx);
    void func_80096FD4(PlayState* play, Room* room);
    void Player_SetBootData(PlayState* play, Player* player);
    void Actor_SpawnTransitionActors(PlayState* play, ActorContext* actorCtx);
    void Object_InitBank(PlayState* play, ObjectContext* objectCtx);
    void LightContext_Init(PlayState* play, LightContext* lightCtx);
    void TransitionActor_InitContext(GameState* state, TransitionActorContext* transiActorCtx);
}

// Default 4-entry (dawn/day/dusk/night) lighting - flat/generic for v1, no per-scene lighting
// authoring in the grid tool yet.
static EnvLightSettings sStairsWarpsF3173LightSettings[4] = {
    {{ 70, 45, 57 }, { 73, -73, 73 }, { 180, 154, 138 }, { -73, 73, -73 }, { 20, 20, 60 },
     { 140, 120, 100 }, (s16)(993 | (1 << 10)), 12800 },
    {{ 105, 90, 90 }, { 73, -73, 73 }, { 255, 255, 240 }, { -73, 73, -73 }, { 50, 50, 90 },
     { 100, 100, 120 }, (s16)(996 | (1 << 10)), 12800 },
    {{ 120, 90, 0 }, { 73, -73, 73 }, { 250, 135, 50 }, { -73, 73, -73 }, { 30, 30, 60 },
     { 120, 70, 50 }, (s16)(995 | (1 << 10)), 12800 },
    {{ 40, 70, 100 }, { 73, -73, 73 }, { 20, 20, 35 }, { -73, 73, -73 }, { 50, 50, 100 },
     { 0, 0, 30 }, (s16)(992 | (1 << 10)), 12800 },
};

// v1 scope has no multi-entrance/exit support - a single spawn index 0.
static EntranceEntry sStairsWarpsF3173Entrances[] = {
    { 0, 0 },
};

// Spawn point authored in the grid tool (grid-space -> world units, see src/shared/geometry.ts).
// params: bits 8-11 = PLAYER_START_MODE_IDLE (0xD - see PLAYER_GET_START_MODE in z64player.h;
// mode 0 is PLAYER_START_MODE_NOTHING, which leaves Player's update/draw entirely inert), low
// byte 0xFF = "no start bg-camera override" (we don't author per-scene camera data).
static ActorEntry sStairsWarpsF3173PlayerSpawn = {
    ACTOR_PLAYER, { 0, 0, 100 }, { 0, -32768, 0 }, 0xDFF
};

// 12 staircase placements (sturdy-bassoon#173), one per storey a staircase serves.
static ActorEntry sStairsWarpsF3173Actors[12] = {
    { ACTOR_RS_STAIRS, { -160, 0, -60 }, { 0, 0x4000, 0 }, RS_STAIR_PARAMS(7944, 0) }, // staircase "Grand stair" row 0: level 0 at (14, 4) facing W
    { ACTOR_RS_STAIRS, { -160, 134, -60 }, { 0, 0x4000, 0 }, RS_STAIR_PARAMS(7944, 1) }, // staircase "Grand stair" row 1: level 1 at (14, 4) facing W
    { ACTOR_RS_STAIRS, { -160, 264, -60 }, { 0, 0x4000, 0 }, RS_STAIR_PARAMS(7944, 2) }, // staircase "Grand stair" row 2: level 2 at (14, 4) facing W
    { ACTOR_RS_STAIRS, { -360, 0, -60 }, { 0, 0x4000, 0 }, RS_STAIR_PARAMS(7945, 0) }, // staircase "Party Room stair" row 0: level 0 at (19, 4) facing W
    { ACTOR_RS_STAIRS, { -360, 104, -60 }, { 0, 0x4000, 0 }, RS_STAIR_PARAMS(7945, 1) }, // staircase "Party Room stair" row 1: level 1 at (19, 4) facing W
    { ACTOR_RS_STAIRS, { -360, 184, -60 }, { 0, 0x4000, 0 }, RS_STAIR_PARAMS(7945, 2) }, // staircase "Party Room stair" row 2: level 2 at (19, 4) facing W
    { ACTOR_RS_STAIRS, { 240, 0, -60 }, { 0, 0x4000, 0 }, RS_STAIR_PARAMS(7946, 0) }, // staircase "Standard stair" row 0: level 0 at (4, 4) facing W
    { ACTOR_RS_STAIRS, { 240, 84, -60 }, { 0, 0x4000, 0 }, RS_STAIR_PARAMS(7946, 1) }, // staircase "Standard stair" row 1: level 1 at (4, 4) facing W
    { ACTOR_RS_STAIRS, { 240, 164, -60 }, { 0, 0x4000, 0 }, RS_STAIR_PARAMS(7946, 2) }, // staircase "Standard stair" row 2: level 2 at (4, 4) facing W
    { ACTOR_RS_STAIRS, { 40, 0, -60 }, { 0, 0x4000, 0 }, RS_STAIR_PARAMS(7947, 0) }, // staircase "Tall stair" row 0: level 0 at (9, 4) facing W
    { ACTOR_RS_STAIRS, { 40, 104, -60 }, { 0, 0x4000, 0 }, RS_STAIR_PARAMS(7947, 1) }, // staircase "Tall stair" row 1: level 1 at (9, 4) facing W
    { ACTOR_RS_STAIRS, { 40, 204, -60 }, { 0, 0x4000, 0 }, RS_STAIR_PARAMS(7947, 2) }, // staircase "Tall stair" row 2: level 2 at (9, 4) facing W
};

static RomFile sStairsWarpsF3173RoomList[] = {
    { (uintptr_t)&stairs_warps_f3_173_room_0_shapeHeader,
      (uintptr_t)&stairs_warps_f3_173_room_0_shapeHeader + 256,
      nullptr },
};

extern "C" int CustomStairsWarpsF3173Scene_IsCustomScene(s32 sceneId) {
    return sceneId == SCENE_STAIRS_WARPS_F3_173;
}

static void InitScene(PlayState* play, s32 spawn) {
    play->curSpawn          = spawn;
    play->linkActorEntry    = nullptr;
    play->unk_11DFC         = nullptr;
    play->setupEntranceList = nullptr;
    play->setupExitList     = nullptr;
    play->cUpElfMsgs        = nullptr;
    play->setupPathList     = nullptr;
    play->numSetupActors    = 0;

    Object_InitBank(play, &play->objectCtx);
    LightContext_Init(play, &play->lightCtx);
    TransitionActor_InitContext(&play->state, &play->transiActorCtx);
    func_80096FD4(play, &play->roomCtx.curRoom);
    YREG(15) = 0;
    gSaveContext.worldMapArea = 0;

    BgCheck_Allocate(&play->colCtx, play, &stairs_warps_f3_173_scene_collisionHeader);

    play->numRooms = 1;
    play->roomList = sStairsWarpsF3173RoomList;

    play->setupEntranceList = sStairsWarpsF3173Entrances;
    play->linkActorEntry    = &sStairsWarpsF3173PlayerSpawn;
    play->linkAgeOnLoad     = gSaveContext.linkAge;

    s16 linkObjectId = gLinkObjectIds[gSaveContext.linkAge];
    ActorDB_Retrieve(play->linkActorEntry->id)->objectId = linkObjectId;
    Object_Spawn(&play->objectCtx, linkObjectId);

    play->objectCtx.subKeepIndex = Object_Spawn(&play->objectCtx, OBJECT_GAMEPLAY_FIELD_KEEP);

    play->skyboxId = SKYBOX_NORMAL_SKY;
    // What SCENE_CMD_SKYBOX_SETTINGS and SCENE_CMD_SKYBOX_DISABLES set in a normal scene: a clear
    // sky, outdoors, sky and sun drawn. PlayState is re-allocated for each scene without being
    // cleared, so skipping them left the previous scene's values in place - Hyrule Field's storm,
    // Link's house's indoor lighting (sturdy-bassoon#122).
    play->envCtx.unk_17 = play->envCtx.unk_18 = 0;
    play->envCtx.indoors         = 0;
    play->envCtx.skyboxDisabled  = 0;
    play->envCtx.sunMoonDisabled = 0;
    play->sequenceCtx.seqId            = NA_BGM_KAKARIKO_KID;
    // NATURE_ID_NONE, never 0xFF: that is NATURE_ID_DISABLED, a save-context value past the end of
    // the ambience table, which z_kankyo.c played at dusk and crashed the audio thread (sturdy-bassoon#156).
    play->sequenceCtx.natureAmbienceId = NATURE_ID_NONE;

    // Normal scenes get this from SCENE_CMD_SOUND_SETTINGS, which resets the audio heap/SFX
    // banks. Our hand-rolled init bypasses the scene command list entirely, so without this call
    // player SFX (footsteps, jump, roll, etc.) and all other one-shot sound effects are silently
    // dropped later in the audio pipeline (BGM is unaffected - it doesn't go through this reset).
    Audio_QueueSeqCmd(0xF0000000);

    play->envCtx.numLightSettings  = 4;
    play->envCtx.lightSettingsList = sStairsWarpsF3173LightSettings;

    Play_InitEnvironment(play, play->skyboxId);
    GameInteractor_ExecuteAfterSceneCommands(play->sceneNum);
}

// The archive prop lists this room draws (sturdy-bassoon#171): plain archive paths, resolved at
// load and baked. Always emitted, so a map's first prop needs no build - only its archive.
static const char* const sStairsWarpsF3173PropLists[] = { "objects/rs_props/stairs_warps_f3_173/props" };

extern "C" void CustomStairsWarpsF3173Scene_InitRoom(PlayState* play, RoomContext* roomCtx) {
    roomCtx->curRoom.echo       = 0;
    roomCtx->curRoom.meshHeader = (MeshHeader*)&stairs_warps_f3_173_room_0_shapeHeader;

    // Normal scenes get these from SCENE_CMD_ROOM_BEHAVIOR; this hand-rolled init bypasses the
    // scene command list, and nothing on the load path clears them - func_80096FD4 resets only
    // num/segment. Without them the room inherits the previous scene's values: a stale
    // ROOM_BEHAVIOR_TYPE1_2 caps R_RUN_SPEED_LIMIT to 5.0 (the short ledge hop instead of the
    // run-off leap) and disables backflip/sidehop/roll. See issue #39.
    roomCtx->curRoom.behaviorType1 = ROOM_BEHAVIOR_TYPE1_0;
    roomCtx->curRoom.behaviorType2 = ROOM_BEHAVIOR_TYPE2_0;
    roomCtx->curRoom.lensMode      = LENS_MODE_HIDE_ACTORS;

    // 12 entries; play->numSetupActors is an s16 (sturdy-bassoon#45), so this is
    // the authored count and not a truncation of it.
    play->numSetupActors = 12;
    play->setupActorList = sStairsWarpsF3173Actors;

    ArchiveProps_DeclareRoom(play, roomCtx, sStairsWarpsF3173PropLists, ARRAY_COUNT(sStairsWarpsF3173PropLists));

    Player_SetBootData(play, GET_PLAYER(play));
    Actor_SpawnTransitionActors(play, &play->actorCtx);
    GameInteractor_ExecuteAfterSceneCommands(play->sceneNum);
}

extern "C" int CustomStairsWarpsF3173Scene_TrySpawn(PlayState* play, s32 sceneId, s32 spawn) {
    if (sceneId != SCENE_STAIRS_WARPS_F3_173) {
        return 0;
    }

    SceneTableEntry* scene = &gSceneTable[sceneId];
    scene->unk_13      = 0;
    play->loadedScene  = scene;
    play->sceneNum     = sceneId;
    play->sceneConfig  = scene->config;
    play->sceneSegment = nullptr;

    InitScene(play, spawn);
    func_80096FE8(play, &play->roomCtx);
    GameInteractor_ExecuteOnSceneInit(play->sceneNum);

    SPDLOG_INFO("CustomStairsWarpsF3173Scene: spawned scene {} spawn {}", sceneId, spawn);
    return 1;
}
