#pragma once
// Shared header for all grid-tool-exported scene C data files.
// Every scene generated by tools/grid-scene-tool includes this instead of
// carrying its own copy, since none of this is scene-specific.
#include "global.h"

// Fast64 uses these names; map them to the Shipwright equivalents from z64.h.
typedef PolygonType0 RoomShapeNormal;
typedef PolygonDlist RoomShapeDListsEntry;
#define ROOM_SHAPE_TYPE_NORMAL 0

// Macros used by Fast64-style collision output that are not in Shipwright public headers.
// COLPOLY_VTX itself lives in z64bgcheck.h (via global.h above): it encodes the engine's vertex-id
// bit layout, so a copy here would silently disagree with the engine the moment that widens.
#define COLPOLY_IGNORE_NONE 0
// SurfaceType.data[0]: wallType[3:0], floorType[7:4], sfxEffect[11:8], exitIdx[20:16], camIdx[31:24]
#define SURFACETYPE0(wallType, floorType, sfxEffect, exitIdx, camIdx, f, g, h) \
    (((wallType) & 0xF) | (((floorType) & 0xF) << 4) | (((sfxEffect) & 0xF) << 8) | \
     (((exitIdx) & 0x1F) << 16) | (((camIdx) & 0x1F) << 24))
// SurfaceType.data[1]: sfx index at bits 3:0 (see D_80119E10 in z_bgcheck.c - e.g. 8 = grass).
// Was previously shifted to bits 27:24, which SurfaceType_GetSfx/func_80041F10 never reads
// (they read data[1] & 0xF), so no footstep sound ever played and every floor silently
// defaulted to index 0 (NA_SE_PL_WALK_GROUND). Bit 27 there is also SurfaceType_IsWallDamage's
// flag, so the old shift was additionally setting that (harmless here since it's only ever
// checked against wall-type polys, but still wrong).
#define SURFACETYPE1(sound, a, b, c, d, e, f, g) ((sound) & 0xF)
