#pragma once
// GENERATED by tools/grid-scene-tool/scripts/make-textures.ts in the sturdy-bassoon repo.
// Do not edit by hand - re-run `npm run make:textures` there. `npm run verify:texture` fails if
// this file and the registry have drifted apart.
//
// Every tiling texture the grid tool's scenes share. 32x32 RGBA16 unless a row below says
// otherwise, stored big-endian because that is how `Interpreter::ImportTextureRgba16` reads it.
//
// These are **raw texture pointers**, not "__OTR__" archive paths - see
// docs/reference/ASSET_PIPELINE.md, "3D textures: a raw array, not an archive path", for why and
// for the four ways this route fails silently.
//
// ALIGN_ASSET(8) is load-bearing, for the opposite reason it is on an archive-path symbol:
// `gfx_check_image_signature` refuses to dereference an *odd* address, so an odd-addressed array
// would take the raw arm by accident rather than by decision, and an aligned one takes it because
// its first seven bytes are not "__OTR__".
#include "align_asset_macro.h"
#include "z64.h"

#ifdef __cplusplus
extern "C" {
#endif

// Generated running-bond masonry (scripts/stoneTexture.ts). No external source.
extern ALIGN_ASSET(8) const u8 gGridToolStoneTex[32 * 32 * 2];

#ifdef __cplusplus
}
#endif
