#pragma once
// GENERATED by tools/grid-scene-tool/scripts/make-stone-texture.ts in the sturdy-bassoon repo.
// Do not edit by hand - re-run `npm run make:texture` there. `npm run verify:texture` fails if
// this file and the generator have drifted apart.
//
// The one tiling stone texture every grid-tool scene shares (issue #86). 32x32 RGBA16, stored
// big-endian because that is how `Interpreter::ImportTextureRgba16` reads it.
//
// This is a **raw texture pointer**, not an "__OTR__" archive path - see the generator for why,
// and docs/reference/ASSET_PIPELINE.md route (b). It is the first of its kind in this tree.
//
// ALIGN_ASSET(8) is load-bearing, for the same reason it is on the archive-path symbols in
// RsItemArt.h and for the opposite outcome: `gfx_check_image_signature` refuses to dereference
// an *odd* address, so an odd-addressed array would take the raw arm by accident rather than by
// decision, and an aligned one takes it because its first seven bytes are not "__OTR__".
#include "align_asset_macro.h"
#include "z64.h"

#define GRID_TOOL_STONE_TEX_WIDTH 32
#define GRID_TOOL_STONE_TEX_HEIGHT 32

#ifdef __cplusplus
extern "C" {
#endif

extern ALIGN_ASSET(8) const u8 gGridToolStoneTex[32 * 32 * 2];

#ifdef __cplusplus
}
#endif
